// import "./add.test";
// import "./find.test";
// import "./cacheBenchmark.test";
// import "./move.test";
// import "./path.test";
// import "./remove.test";
// import "./duplicate.test";
// import "./import.test";
// import "./render.test";
import "./lazyCache.test";
// import "./debug.test";
import { KT_Core } from "kt-core";
import { runTests } from "kt-testing-suite-core";
KT_Core.init();
runTests();
